version: '3.8'
services:
    influencer:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_HOST: influencer_db
            DB_DATABASE: influencer
            DB_USERNAME: admin1
            DB_PASSWORD: admin1
        command: 'php artisan serve --host=0.0.0.0 --port=8000'
        ports:
            - 8003:8000
        depends_on:
            - influencer_db

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        environment:
            DB_HOST: influencer_db
            DB_DATABASE: influencer
            DB_USERNAME: admin1
            DB_PASSWORD: admin1
        depends_on:
            - influencer_db

    influencer_db:
        container_name: influencer_db
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: influencer
            MYSQL_USER: admin1
            MYSQL_PASSWORD: admin1
            MYSQL_ROOT_PASSWORD: admin1
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33070:3307

    redis-server:
        container_name: redis
        image: redis:latest
        ports:
        - 6379:6379
