version: '3.8'
services:
    queue:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_HOST: db
            DB_DATABSE: emails
            DB_USERNAME: admin1
            DB_PASSWORD: admin1
        command: 'php artisan queue:work'
        depends_on:
            - db

    db:
        container_name: emails_db
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: emails
            MYSQL_USER: admin1
            MYSQL_PASSWORD: admin1
            MYSQL_ROOT_PASSWORD: admin1
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33067:3306

